Add user comment to contact form
buerokratt/Chat-Widget pull request #90
Opened 2024-02-15 02:29 UTC by baha-a

Fixes:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1#issuecomment-1938799114

2024-02-15 09:49 UTC, 1AhmedYasser requested changes

2024-02-15 09:49 UTC, 1AhmedYasser commented on src/translations/et/common.json
> -  "widget.action.forward-email": "Teie e-postiaadress",
Please revert waiting time removed translations as it they will be referenced here https://github.com/buerokratt/Buerokratt-Chatbot/issues/445

2024-02-15 09:49 UTC, 1AhmedYasser commented on src/translations/en/common.json
> -  "widget.form.email": "Your email address",
Please revert waiting time removed translations as it they will be referenced here https://github.com/buerokratt/Buerokratt-Chatbot/issues/445

2024-02-15 09:49 UTC, 1AhmedYasser commented on src/components/waiting-time-notification/info-icon.tsx
Please revert waiting time notification as it they will be referenced here https://github.com/buerokratt/Buerokratt-Chatbot/issues/445

2024-02-15 09:49 UTC, 1AhmedYasser commented on src/components/waiting-time-notification/notification-message.tsx
Please revert waiting time notification as it they will be referenced here https://github.com/buerokratt/Buerokratt-Chatbot/issues/445

2024-02-15 09:49 UTC, 1AhmedYasser commented on src/components/waiting-time-notification/waiting-time-notification-form-success.tsx
Please revert waiting time notification as it they will be referenced here https://github.com/buerokratt/Buerokratt-Chatbot/issues/445

2024-02-15 09:49 UTC, 1AhmedYasser commented on src/components/waiting-time-notification/waiting-time-notification-form.tsx
Please revert waiting time notification as it they will be referenced here https://github.com/buerokratt/Buerokratt-Chatbot/issues/445

2024-02-15 09:49 UTC, 1AhmedYasser commented on src/components/waiting-time-notification/waiting-time-notification.module.scss
Please revert waiting time notification as it they will be referenced here https://github.com/buerokratt/Buerokratt-Chatbot/issues/445

2024-02-15 09:49 UTC, 1AhmedYasser commented on src/components/waiting-time-notification/waiting-time-notification.test.tsx
Please revert waiting time notification as it they will be referenced here https://github.com/buerokratt/Buerokratt-Chatbot/issues/445

2024-02-15 09:49 UTC, 1AhmedYasser commented on src/components/waiting-time-notification/waiting-time-notification.tsx
Please revert waiting time notification as it they will be referenced here https://github.com/buerokratt/Buerokratt-Chatbot/issues/445

2024-02-15 09:57 UTC, 1AhmedYasser commented
in here 

```
 const submitForm = async (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    if (validateInput(endUserContacts)) {
      await WidgetService.sendContactInfo(
        chatId ?? "",
        endUserContacts.mailAddress,
        endUserContacts.phoneNr
      ).catch(console.error);
      const newMsg = getContactFormFulfilledNewMessage(
        endUserContacts,
        chatId,
        contactMsgId,
        t
      );
      dispatch(sendMessageWithNewEvent(newMsg));
      dispatch(setShowUnavailableContactForm(false));
      newMsg.content = "";
      dispatch(sendMessagePreview(newMsg));
      dispatch(
        endChat({
          event: CHAT_EVENTS.UNAVAILABLE_CONTACT_INFORMATION_FULFILLED,
          isUpperCase: false,
        })
      );
      dispatch(setShowUnavailableContactForm(false));
    }
  };
```

you should check if the user left a comment, if he does then send a message before calling `dispatch(endchat)`
the message content should be something as follows

`content: 'User Question:\n${question}'`

2024-02-15 23:40 UTC, baha-a commented
Requested changes resolved.

2024-02-16 02:08 UTC, 1AhmedYasser approved these changes

2024-02-16 09:09 UTC, merged